### ISSUE TITLE
Test Initializer to add billable services in billing module

### ISSUE THREAD

**Issue by michaelbontyes** [MadiroGlobalHealth/UVL-EMR#12]
The billing domain has been added to the Initializer module:
https://github.com/mekomsolutions/openmrs-module-initializer/tree/main?tab=readme-ov-file#version-280

We can already test it out in preparation of receiving the validated billable services to add for the project.

**Comment by WodPachua** [comment]
Is it just testing if new/custom service concepts can be loaded? @michaelbontyes

**Comment by michaelbontyes** [comment]
@WodPachua, Yes. Does it work using the Initializer?

**Comment by WodPachua** [comment]
Yes It does... though not sure what your acceptance criteria is for the test... @michaelbontyes

**Comment by michaelbontyes** [comment]
Hi @WodPachua , do you have an example where you have been able to use the iniz to add the individual costs and payement methods to each billable services added? (We know how to populate the list of payement methods, but here is about the cost of each billable service depending on the payement method) Thanks

![Image](https://github.com/user-attachments/assets/c3907392-62c9-446a-8b62-3e02fa69f688)

**Comment by WodPachua** [comment]
Oh I see.. I had a[ blocker thas has just been fixed](https://github.com/mekomsolutions/openmrs-module-initializer/commit/ab9e8c0e45b4cce2e01c8b642777fd637319b888) this morning... let me do that and share

**Comment by sherrif10** [comment]
Hello @WodPachua , Any progress on this ?

**Comment by WodPachua** [comment]
@michaelbontyes @sherrif10 Apparently, the initializer can only add billable services, service types, payment modes, and cash points, but not the prices of the services. I have tried a couple of ways but have not been successful yet.

This means, we can add the services, but can't use them in the EMR since they don't have prices, and their attached payment modes

The other option I found to work was posting them via the API, which works just fine... including the services, with their prices and payment modes,

**Comment by michaelbontyes** [comment]
Thank you @WodPachua. Would you be comfortable pairing up with Jonathan Odora to extend the Iniz to support prices as well?

**Comment by WodPachua** [comment]
Sure... no problem...
