### ISSUE TITLE
Add the Data Visualizer module from UgandaEMR

### ISSUE THREAD

**Issue by michaelbontyes** [MadiroGlobalHealth/UVL-EMR#24]
Using the frontend (and backend if needed) configuration files for modules, add the Data visualizer module: https://github.com/METS-Programme/esm-ugandaemr-data-visualizer/tree/main

Example:
![Image](https://github.com/user-attachments/assets/3d0ea8e4-cbd3-4f41-8dd3-0e0c6ccfbdde)

UVL frontend modules config:
https://github.com/MadiroGlobalHealth/UVL-EMR/blob/main/distro/configs/openmrs/frontend_assembly/reference-application-spa-assemble-config.json

UVL backend modules config:
https://github.com/MadiroGlobalHealth/UVL-EMR/blob/a8e776d7088e4fd3ae260b2aec49296b3c6d3853/distro/pom.xml#L29-L40

**Comment by dancinoman** [comment]
If I understand very well, I should add this module to distro level configuration?

**Comment by michaelbontyes** [comment]
Hi @dancinoman , yes modules are configured at the distro level so that all sites will use the same version which simplifies maintenance

**Comment by dancinoman** [comment]
Here is my situation up-to-date:

1. The configuration of the front-end "reference-application-spa-assemble-config.json" is exactly the same on the link above so no change has been made. The pom.xml contains the same line of code above as well hence no change has been made.
2. When I run local host through './start.sh' command it runs normaly but the option Data vizualizer is not showing up in the option of dropdown in order to display on the left navigation bar.
3. When I run local host through 'yarn start' command I can try to log as usual but it stops an throw this error in my browser 'An error has occurred. Please try reloading the page.' 

Is there something that I am missing?

**Comment by sherrif10** [comment]
Did you add esm-data-visualizer under https://github.com/MadiroGlobalHealth/UVL-EMR/blob/main/distro/configs/openmrs/frontend_assembly/reference-application-spa-assemble-config.json#L3  checkout how it was done here for [lab order module](https://github.com/MadiroGlobalHealth/UVL-EMR/commit/b7f899e382bfdddf495069edd15f1770c1bba093)

**Comment by dancinoman** [comment]
![Image](https://github.com/user-attachments/assets/adfcce02-2406-4066-906e-88c053e60dc1)
Like this and the option still not showing up

**Comment by dancinoman** [comment]
![Image](https://github.com/user-attachments/assets/9c1f93cd-c71e-4e5f-8639-cd19afa83503)
What does it mean? and how can we fix it?

https://github.com/dancinoman/UVL-EMR

**Comment by michaelbontyes** [comment]
Here is the link to the frontend module on NPM: https://www.npmjs.com/package/@ugandaemr/esm-data-visualizer-app
What to add in the config frontend: @ugandaemr/esm-data-visualizer-app

**Comment by tendomart** [comment]
@michaelbontyes  was this done?

**Comment by tendomart** [comment]
I also noticed the Datav Visualizer is still in pre-release version.. so still waiting for METS feedback at https://talk.openmrs.org/t/ugandaemr-data-visualizer-and-reporting/43699

**Comment by tendomart** [comment]
@michaelbontyes  I checkes the visualizer  it's in pre-release state and teh METS team have not responded very well on the issue, can we just go ahead with it. because it looks like it's the only available esm option at the moment. The Sol Develo team (Pawel), too did some work but they' not responded back too.

**Comment by dancinoman** [comment]
I did miss that. How do you know it is in prerelease state? I have checked every where on the project they have made and did not notice that.

**Comment by tendomart** [comment]
Hi  @dancinoman  I think we have a green flag. 

https://www.npmjs.com/package/@ugandaemr/esm-data-visualizer-app/v/1.0.1-pre.43?activeTab=versions

but even in that state i talked to Isaac, one of the developers and he told me they're using it in 184 facilities. Though still under development.

So we can go

**Comment by dancinoman** [comment]
Allright. Just want to say I haven't found a way to make it work so far. Tell me if you are experiencing issues with that module.

**Comment by tendomart** [comment]
Good news just keep going
